### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by imemineimemineimemine** [ZirtysPerzys/DRGL-wallet#27]
wallet wont start in terminal
<code>fango-wallet_3.1.0/fango-wallet: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory</code> Ubuntu 16.04

**Comment by aejontargaryen** [comment]
You may need to install QT
Try
 `sudo apt-get install qt5-default`
